// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to identify the taxonomic classification of an organism from an image.
 *
 * - identifyOrganism - A function that handles the organism identification process.
 * - IdentifyOrganismInput - The input type for the identifyOrganism function.
 * - IdentifyOrganismOutput - The return type for the identifyOrganism function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyOrganismInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of an organism, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type IdentifyOrganismInput = z.infer<typeof IdentifyOrganismInputSchema>;

const IdentifyOrganismOutputSchema = z.object({
  domain: z.string().describe('The domain of the organism.'),
  kingdom: z.string().describe('The kingdom of the organism.'),
  phylum: z.string().describe('The phylum of the organism.'),
  class: z.string().describe('The class of the organism.'),
  order: z.string().describe('The order of the organism.'),
  family: z.string().describe('The family of the organism.'),
  genus: z.string().describe('The genus of the organism.'),
  species: z.string().describe('The species of the organism.'),
  confidence: z
    .number()
    .describe('A confidence score (0-1) for the identification.'),
});
export type IdentifyOrganismOutput = z.infer<typeof IdentifyOrganismOutputSchema>;

export async function identifyOrganism(input: IdentifyOrganismInput): Promise<IdentifyOrganismOutput> {
  return identifyOrganismFlow(input);
}

const prompt = ai.definePrompt({
  name: 'identifyOrganismPrompt',
  input: {schema: IdentifyOrganismInputSchema},
  output: {schema: IdentifyOrganismOutputSchema},
  prompt: `You are an expert biologist specializing in the taxonomic classification of organisms.

You will use the image provided to identify the organism's taxonomic classification, including its domain, kingdom, phylum, class, order, family, genus, and species. You will also provide a confidence score (0-1) for your identification.

Analyze the following image to identify the organism:

{{media url=photoDataUri}}

Ensure that the output is structured according to the IdentifyOrganismOutputSchema, with each taxonomic rank accurately identified and the confidence score reflecting the certainty of the identification.
`,
});

const identifyOrganismFlow = ai.defineFlow(
  {
    name: 'identifyOrganismFlow',
    inputSchema: IdentifyOrganismInputSchema,
    outputSchema: IdentifyOrganismOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
