// This is an autogenerated file from Firebase Genkit.
'use server';
/**
 * @fileOverview Summarizes key characteristics and interesting facts about an organism.
 *
 * - organismSummarizer - A function that summarizes the organism.
 * - OrganismSummarizerInput - The input type for the organismSummarizer function.
 * - OrganismSummarizerOutput - The return type for the organismSummarizer function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const OrganismSummarizerInputSchema = z.object({
  domain: z.string().describe('The domain of the organism.'),
  kingdom: z.string().describe('The kingdom of the organism.'),
  phylum: z.string().describe('The phylum of the organism.'),
  class: z.string().describe('The class of the organism.'),
  order: z.string().describe('The order of the organism.'),
  family: z.string().describe('The family of the organism.'),
  genus: z.string().describe('The genus of the organism.'),
  species: z.string().describe('The species of the organism.'),
});
export type OrganismSummarizerInput = z.infer<typeof OrganismSummarizerInputSchema>;

const OrganismSummarizerOutputSchema = z.object({
  summary: z.string().describe('A summary of the key characteristics and interesting facts about the organism.'),
});
export type OrganismSummarizerOutput = z.infer<typeof OrganismSummarizerOutputSchema>;

export async function organismSummarizer(input: OrganismSummarizerInput): Promise<OrganismSummarizerOutput> {
  return organismSummarizerFlow(input);
}

const prompt = ai.definePrompt({
  name: 'organismSummarizerPrompt',
  input: {schema: OrganismSummarizerInputSchema},
  output: {schema: OrganismSummarizerOutputSchema},
  prompt: `You are an expert in summarizing information about organisms based on their taxonomy.

  Provide a concise summary of the key characteristics and interesting facts about the organism defined by the following taxonomy:

  Domain: {{{domain}}}
  Kingdom: {{{kingdom}}}
  Phylum: {{{phylum}}}
  Class: {{{class}}}
  Order: {{{order}}}
  Family: {{{family}}}
  Genus: {{{genus}}}
  Species: {{{species}}}

  Summary:`,
});

const organismSummarizerFlow = ai.defineFlow(
  {
    name: 'organismSummarizerFlow',
    inputSchema: OrganismSummarizerInputSchema,
    outputSchema: OrganismSummarizerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
